[builder]
name = "heroku/buildpacks:20"

[build]
phpVersion = "8.2.0"

[deploy]
startCommand = "php -S 0.0.0.0:8000 -t public"
healthCheckPath = "/"
healthCheckTimeout = 30

[[services]]
name = "web"
httpPort = 8000
