[builder]
name = "heroku/buildpacks:20"

[build]
phpVersion = "8.2.0"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthCheckPath = "/"
healthCheckTimeout = 300

[[services]]
name = "web"
httpPort = 8000
